---
title: "Seminar descriptive statistics 2020-10-08"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
```


## How to look for help


## How to look for error in the code



```{r}

hypertrophy <- read_csv("./data/hypertrophy.csv")
# read_csv is from the package readr


var_interest <- c("SUB_ID", 
                  "GROUP", 
                  "CLUSTER", 
                  "AGE", 
                  "T1_BODY_MASS",
                  "PERCENT_TYPE_II_T1",
                  "Squat_3RM_kg", 
                  "DXA_LBM_1", 
                  "DXA_FM_T1",
                  "SQUAT_VOLUME")

hyp2 <- hypertrophy %>%
  select(all_of(var_interest)) %>%
  print()
# Specify all_of(var_interest) to selet variables correctly



# Now the data set only contains participants from 
# the two groups (clusters)

hyp2 %>%
  filter(!is.na(CLUSTER)) %>%
  
  select(-GROUP) %>%

  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = AGE:SQUAT_VOLUME) %>%
  group_by(CLUSTER, variable) %>%

  summarise(m = mean(value), 
            s = sd(value)) %>% 
    mutate(ms = paste(round(m, 1), 
                    " (", 
                    round(s, 1), 
                    ")", sep = ""),
  
         
         CLUSTER = factor(CLUSTER, 
                          levels = c("LOW", "HIGH"), 
                          labels = c("LOW (n = 10)", 
                                     "HIGH (n = 10)")),
 
         
         variable = factor(variable, 
                           levels = c("AGE", 
                                      "T1_BODY_MASS", 
                                      "DXA_LBM_1", 
                                      "DXA_FM_T1", 
                                      "PERCENT_TYPE_II_T1", 
                                      "Squat_3RM_kg", 
                                      "SQUAT_VOLUME"), 
                           labels = c("Age (years)", 
                                      "Body mass (kg)", 
                                      "LBM (kg)", 
                                      "FM (kg)", 
                                      "Type II (%)", 
                                      "Squat 3RM (kg)", 
                                      "Total training volume (kg)"))) %>%
 
  select(-m, -s) %>%

  pivot_wider(names_from = CLUSTER, 
              values_from = ms) %>%
  arrange(variable) %>%
  select(variable, `LOW (n = 10)`, `HIGH (n = 10)`) %>%
  
  print()

```

## Import data
```{r}
library(readxl)
rel <- read_excel("data/reliability.xlsx", na = "NA")
```


## Write code in sequence

```{r}

## Purpose: calculate technical error for strength

## Load packages
library(readxl)
library(tidyverse)

## Load data 
dat <- read_excel("./data/reliability.xlsx") %>%
  print()

##

dat %>%
  # remove vo2max by select
  select(- vo2max) %>%
  # make data in wide format on variable per timepoint
  pivot_wider(names_from = timepoint, 
              values_from = strength) %>%
  #  Calculate difference between t1 and t2:
  mutate(diff = t2- t1) %>%
## Calculate sd of the difference
  ## Calculate te as sd(diff) / sqrt(2)
  summarise(sd.diff = sd(diff),
            te = sd.diff / sqrt(2)) %>%
  print()


## Load data 
dat <- read_excel("./data/reliability.xlsx") %>%
  print()



```






